### ISSUE TITLE
FR: add IUP

### ISSUE THREAD

**Issue by iahung2** [brechtsanders/winlibs_recipes#64]
https://sourceforge.net/projects/iup/

**Comment by brechtsanders** [comment]
Recipe already exists [here](https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes_work_in_progress/iup.winlib), but  building was not successful, mainly because the following dependencies are also not building yet:
- [cd](https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes_work_in_progress/cd.winlib)
- [imtoolkit](https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes_work_in_progress/imtoolkit.winlib)
